# Generated by Django 6.0 on 2026-01-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Введите Ссылка на платеж",
                max_length=400,
                null=True,
                verbose_name="Ссылка на платеж",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Введите Ссесия ID",
                max_length=255,
                null=True,
                verbose_name="Ссесия ID",
            ),
        ),
    ]
