# Generated by Django 6.0 on 2026-01-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_payment_method_alter_payment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Введите Ссылка на платеж",
                max_length=4000,
                null=True,
                verbose_name="Ссылка на платеж",
            ),
        ),
    ]
